import INITIAL_HOLLOW_KNIGHT_CHECKLIST_STATE from './INITIAL_HOLLOW_KNIGHT_CHECKLIST_STATE';
import INITIAL_SILKSONG_CHECKLIST_STATE from './INITIAL_SILKSONG_CHECKLIST_STATE';

const INITIAL_CHECKLIST_STATE = {
    'hollow-knight': INITIAL_HOLLOW_KNIGHT_CHECKLIST_STATE,
    silksong: INITIAL_SILKSONG_CHECKLIST_STATE,
} as const;

export default INITIAL_CHECKLIST_STATE;
